### ISSUE TITLE
Question: batch size

### ISSUE THREAD

**Issue by sealedtx** [dog-qiuqiu/MobileNetv2-YOLOV3#10]
@dog-qiuqiu Hi! Thank you for your work. Please clarify why batch is so small (16) comparing to default yolov3 (64):
https://github.com/dog-qiuqiu/MobileNetv2-YOLOV3/blob/2cda47a036e0378cb6c988326c3b53016eeb2b4f/MobileNetV2-YOLOv3-SPP/MobileNetV2-YOLOv3-SPP.cfg#L2

**Comment by dog-qiuqiu** [comment]
Because I have x8 GPUs, my batch size is X8. I suggest that the batch size should not be less than 128

**Comment by sealedtx** [comment]
@dog-qiuqiu Great, thanks for a quick answer!
