### ISSUE TITLE
How to train yoloface-500k.

### ISSUE THREAD

**Issue by beaconhappiness** [dog-qiuqiu/MobileNetv2-YOLOV3#36]
I hope to train yoloface-500k model on custom database.
How to train this model?
Where can I get trainer for this model.

**Comment by eltonfernando** [comment]
use https://github.com/tzutalin/labelImg for annotation

use the repository of AlexeyAB
git clone https://github.com/AlexeyAB/darknet

Follow the README.md instructions for your operating system
